default-cache-ttl 43200
max-cache-ttl 43200
pinentry-program /opt/homebrew/bin/pinentry-mac
enable-ssh-support
scdaemon-program /Applications/GPG Tap Notifier.app/Contents/Library/GPG Tap Notifier Agent.app/Contents/MacOS/GPG Tap Notifier Agent
