# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.bin:/usr/local/bin:$PATH
export PATH=$HOME/Library/Python/3.8/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

eval "$(/opt/homebrew/bin/brew shellenv)"

# Adams aws profile switcher
awp() { awp_run $@; . /tmp/aws_profile; }

#PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded
# ZSH_THEME="agnoster"
source ~/powerlevel10k/powerlevel10k.zsh-theme

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf
)

source $ZSH/oh-my-zsh.sh
source <(kubectl completion zsh)
# export PS1='$(kube_ps1)'$PS1
# source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
# export PROMPT='$(kube_ps1)'$PROMPT

# Do not share history between sessions
setopt noincappendhistory
setopt nosharehistory

# User configuration
export HISTSIZE=10000
export SAVEHIST=10000

# Use a git editor wrapper so failures are hard to miss.
export GIT_EDITOR="$HOME/.bin/git-editor-notice"

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
alias history='history -i 1 | less +G'
alias landscape='tee /tmp/landscape && cat /tmp/landscape| landscape'

alias k='kubecolor'
alias kubectl='kubecolor'
alias i='istioctl'
alias lgit='lazygit'
alias docker='podman'
alias k9s='k9s -A'
alias zed='/Applications/Zed.app/Contents/MacOS/cli'
alias cat='bat --paging=never'
alias ls='lsd'
alias ll='lsd -lh'
alias la='lsd -lAh'
alias lt='lsd --tree'


# trufflehog-exclude() { echo "^$1$" >> ~/.trufflehog-global-ignore && echo "Excluded $1 globally for Trufflehog"; }

trufflehog-exclude() {
  fp="$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
  fn="$(basename "$1")"
  rp="$1"  # relative path as provided
  echo "^$fp\$" >> ~/.trufflehog-global-ignore
  echo "^(\\./)?${rp}\$" >> ~/.trufflehog-global-ignore
  echo "^(\\./)?$fn\$" >> ~/.trufflehog-global-ignore
  echo "Excluded $fp, ./$rp, and ./$fn globally for Trufflehog"
}


# source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Krew is a special baby
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Used for customer separation using direnv
# eval "$(direnv hook zsh)"
export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye > /dev/null

[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"
